Models/TaiKhoan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.PhanQuyenChucNangs = new HashSet<PhanQuyenChucNang>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        public string HoVaTen { get; set; }
        public string SoDienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanQuyenChucNang> PhanQuyenChucNangs { get; set; }
    }
}

Areas/Admin/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebThucPham.Models;

namespace WebThucPham.Areas.Admin.Controllers
{
    public class TaiKhoanController : Controller
    {
        // GET: Admin/TaiKhoan
        public ActionResult DanhSach()
        {
            return View(new mapTaiKhoan().DanhSach());
        }

        public ActionResult ChiTiet(string username)
        {
            return View(new mapTaiKhoan().ChiTiet(username));

        }
        public ActionResult LuuPhanQuyen(string username, string chucnang, bool? check)
        {
            var map = new mapPhanQuyenChucNang();
            map.LuuPhanQuyen(username, chucnang, check ?? false); // Gán giá trị mặc định là false nếu check là null
            return RedirectToAction("ChiTiet", new { username = username });
        }



    }
}

Areas/Admin/Views/TaiKhoan/ChiTiet.cshtml
@model WebThucPham.Models.TaiKhoan

@{
    ViewBag.Title = "ChiTiet";
    Layout = "~/Areas/Admin/Views/Shared/layout-admin.cshtml";
    var listQuyen = new WebThucPham.Models.mapPhanQuyenChucNang().QuyenTaiKhoan(Model.Username);
    var listNhom = listQuyen.Select(m => m.NhomChucNang).Distinct();

}

<h2>Chi tiết tài khoản</h2>
<div class="row">
    <!-- Cột phân quyền -->
    <div class="col-md-8">
        <h4>Phân quyền</h4>
        <hr />
        <table class="table table-bordered">
            @foreach (var nhom in listNhom)
            {
                var listCN = listQuyen.Where(m => m.NhomChucNang == nhom).ToList();

                <tr>
                    <td>@nhom</td>

                    @foreach (var cn in listCN)
                    {
                        <td>
                            <form action="@Url.Action("LuuPhanQuyen", "TaiKhoan", new { area = "Admin" })" id="@Model.Username-@cn.Code" autocomplete="off">
                                <input type="hidden" name="username" value="@Model.Username" />
                                <input type="hidden" name="chucnang" value="@cn.Code" />
                                <input type="checkbox" @(cn.DaChon > 0 ? "checked" : "") value="true" name="check" onchange="this.form.submit()" />
                                @cn.MoTa
                            </form>
                        </td>
                    }
                </tr>
            }
        </table>
    </div>
</div>

<!-- Cột chi tiết tài khoản -->
<div class="col-md-4">
    <h4>Tài khoản</h4>
    <hr />
    <table class="table table-bordered table-striped">
        <tbody>
            <tr>
                <th>Mật khẩu</th>
                <td>@Html.DisplayFor(model => model.Password)</td>
            </tr>
            <tr>
                <th>Họ và tên</th>
                <td>@Html.DisplayFor(model => model.HoVaTen)</td>
            </tr>
            <tr>
                <th>Số điện thoại</th>
                <td>@Html.DisplayFor(model => model.SoDienThoai)</td>
            </tr>
        </tbody>
    </table>
</div>


<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.Username }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-secondary" })
</p>

Areas/Admin/Views/TaiKhoan/DanhSach.cshtml
@model IEnumerable<WebThucPham.Models.TaiKhoan>
@{
    ViewBag.Title = "Danh sách tài khoản";
    Layout = "~/Areas/Admin/Views/Shared/layout-admin.cshtml";
}

<div class="container">
<h2>DanhSach</h2>
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Username)</th>
            <th>@Html.DisplayNameFor(model => model.Password)</th>
            <th>@Html.DisplayNameFor(model => model.HoVaTen)</th>
            <th>@Html.DisplayNameFor(model => model.SoDienThoai)</th>
           
        </tr>
        @foreach(var item in Model)
            {
                <tr>
                    <td>
                    <a href="~/Admin/TaiKhoan/ChiTiet?username=@item.Username">
                        @Html.DisplayFor(modelItem => item.Username)
                    </a>
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Password)</td>

                    <td>@Html.DisplayFor(modelItem => item.HoVaTen)</td>

                    <td>@Html.DisplayFor(modelItem => item.SoDienThoai)</td>

                </tr>
            }
    </table>
</div>